import React from "react";

export const metadata = {
  title: "Contact us",
  description: "Generated by create next app",
};

const FormLayout = ({ children }) => {
  return <div>{children}</div>;
};

export default FormLayout;
