import { Montserrat } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";

import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <main>{children}</main>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
