import { Montserrat } from "next/font/google";
import "modern-normalize";

import { Layout } from "@/components/Layout/Layout";
import { Header } from "@/components/Header/Header";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Point",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Layout>
          <Header />
          {children}
        </Layout>
      </body>
    </html>
  );
}
