import React from "react";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

const PortfolioLayout = ({ children }) => {
  return <div>{children}</div>;
};

export default PortfolioLayout;
